name: Python Tests and CI/CD

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Change this to your required Python version

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flask flask-cors flask-mysqldb werkzeug pandas numpy joblib

      - name: Debug Installed Packages
        run: |
          source venv/bin/activate
          python -m pip list  # Check installed packages

      - name: Run Pytest
        run: |
          source venv/bin/activate
          pytest Backend/tests/ --maxfail=5 --disable-warnings -v

      - name: Debug Python Paths
        run: |
          source venv/bin/activate
          which python
          which pytest
